// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderStatus int32

const (
	OrderStatus_INIT            OrderStatus = 0
	OrderStatus_WAITING_CONFIRM OrderStatus = 1
	OrderStatus_PAID            OrderStatus = 2
)

var OrderStatus_name = map[int32]string{
	0: "INIT",
	1: "WAITING_CONFIRM",
	2: "PAID",
}

var OrderStatus_value = map[string]int32{
	"INIT":            0,
	"WAITING_CONFIRM": 1,
	"PAID":            2,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

type Order struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int64       `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  int64       `protobuf:"varint,3,opt,name=tax,proto3" json:"tax,omitempty"`
	CreatedAt            int64       `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status               OrderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetTax() int64 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_INIT
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterEnum("order.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*Response)(nil), "order.Response")
}

func init() {
	proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2)
}

var fileDescriptor_986e030a471601a2 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x36, 0xdd, 0x3a, 0xbb, 0xd7, 0xb2, 0x95, 0xa7, 0x60, 0x10, 0x84, 0xd2, 0x53, 0x19, 0x3a,
	0xa1, 0x82, 0xf7, 0x32, 0x51, 0x73, 0xb0, 0x93, 0x38, 0xf1, 0x38, 0x6a, 0x93, 0x43, 0x11, 0x6c,
	0x49, 0x32, 0xf1, 0x37, 0xf8, 0xab, 0xa5, 0x49, 0x95, 0x79, 0xf1, 0x12, 0xde, 0xf7, 0x7d, 0x2f,
	0xf9, 0xbe, 0x97, 0x07, 0x27, 0x9d, 0x6a, 0x4d, 0x7b, 0xd9, 0x2a, 0x21, 0x95, 0x3b, 0x97, 0x96,
	0x41, 0xdf, 0x82, 0xf4, 0x8b, 0x80, 0xbf, 0xee, 0x2b, 0x9c, 0x81, 0xd7, 0x08, 0x4a, 0x12, 0x92,
	0x4d, 0xb9, 0xd7, 0x08, 0x3c, 0x06, 0xbf, 0x53, 0x4d, 0x2d, 0xa9, 0x97, 0x90, 0x6c, 0xc4, 0x1d,
	0xc0, 0x18, 0x46, 0xa6, 0xfa, 0xa4, 0x23, 0xcb, 0xf5, 0x25, 0x9e, 0x01, 0xd4, 0x4a, 0x56, 0x46,
	0x8a, 0x6d, 0x65, 0xe8, 0xd8, 0x0a, 0xd3, 0x81, 0x29, 0x0c, 0x2e, 0x60, 0xa2, 0x4d, 0x65, 0x76,
	0x9a, 0xfa, 0x09, 0xc9, 0x66, 0x39, 0x2e, 0x5d, 0x0a, 0x6b, 0xfa, 0x64, 0x15, 0x3e, 0x74, 0xa4,
	0xf7, 0x10, 0x70, 0xa9, 0xbb, 0xf6, 0x5d, 0x4b, 0xa4, 0x70, 0xa8, 0x77, 0x75, 0x2d, 0xb5, 0xb6,
	0x99, 0x02, 0xfe, 0x03, 0x31, 0x05, 0x97, 0xdd, 0x06, 0x0b, 0xf3, 0x68, 0xff, 0x41, 0xee, 0xa4,
	0xc5, 0x35, 0x84, 0x7b, 0x06, 0x18, 0xc0, 0x98, 0x95, 0x6c, 0x13, 0x1f, 0xe0, 0x11, 0xcc, 0x5f,
	0x0a, 0xb6, 0x61, 0xe5, 0xdd, 0x76, 0xb5, 0x2e, 0x6f, 0x19, 0x7f, 0x88, 0x49, 0x2f, 0x3f, 0x16,
	0xec, 0x26, 0xf6, 0xf2, 0x37, 0x88, 0xdc, 0x3d, 0xa9, 0x3e, 0xfa, 0x71, 0xcf, 0x21, 0x5c, 0xd9,
	0x51, 0xdc, 0x1f, 0xfd, 0xf1, 0x3a, 0x9d, 0x0f, 0xe8, 0x37, 0xf3, 0x05, 0x44, 0xcf, 0x9d, 0xa8,
	0x8c, 0x1c, 0x6c, 0xff, 0x6f, 0x7f, 0x9d, 0xd8, 0x4d, 0x5c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x60, 0xf1, 0x8a, 0x4a, 0xa4, 0x01, 0x00, 0x00,
}
